# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, modulesPath
, ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-244e4924-8880-4676-9db2-d92ea2568bda";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-244e4924-8880-4676-9db2-d92ea2568bda".device = "/dev/disk/by-uuid/244e4924-8880-4676-9db2-d92ea2568bda";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/396F-37D2";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    {
      device = "/dev/mapper/luks-10050cf8-5c4d-44b9-8dd3-7b306ef47c0e";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enabledRedistributableFirmware;
}
