# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, modulesPath
, ...
}:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/98448f59-d342-4caa-8995-5f18ab9ba4e7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/D83D-5BFA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/var/lib/docker/rootfs/overlayfs/1345bfd655867fe9dfc2271e0f476dc4074054c620b2935fcef4878940c3e3c4" =
    {
      device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/rootfs/overlayfs/be2141ab5798aed284b728760aefc8311fcd853245391ff859adc6e8e54f31ff" =
    {
      device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/mnt/BIGDISK" =
    {
      device = "/dev/disk/by-uuid/5d438092-b767-4a88-ab63-0e2fb04685a5";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/9cbcb9e7-6281-4d05-a973-4ab8634c7dd0"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
